#!/usr/bin/python
import random

max_size = 5
max_value = 5
count_of_items = 10

with open("test_items.txt", "w+") as file:
    file.write(str(count_of_items) + "\n")
    for i in range(count_of_items):
        file.write(str(random.randint(1, max_size)) + " " +
                   str(random.randint(1, max_value)) + "\n")
